version: '3.8'

services:
  build-img:
    build:
        context: .
        dockerfile: dockerfile
        args:
            LAST_UPDATE: "02.02.2025 14:45"
            LAST_MAJOR_UPDATE: "02.02.2025 14:45"
    image: registry.mokican.com/kasm-ubuntu-jng:1.16-jammy
